version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/StatusChecker"
    schedule:
      interval: "weekly"
      
    reviewers:
      - "philipp-c-moser"
      
    target-branch: "develop"


  - package-ecosystem: "nuget"
    directory: "/StatusChecker.iOS"
    schedule:
      interval: "weekly"
      
    reviewers:
      - "philipp-c-moser"
      
    target-branch: "develop"
