//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatusChecker.I18N {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppTranslations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppTranslations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StatusChecker.I18N.AppTranslations", typeof(AppTranslations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Main_Button_Title_Add {
            get {
                return ResourceManager.GetString("Main_Button_Title_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Main_Button_Title_Back {
            get {
                return ResourceManager.GetString("Main_Button_Title_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Main_Button_Title_Cancel {
            get {
                return ResourceManager.GetString("Main_Button_Title_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Main_Button_Title_Delete {
            get {
                return ResourceManager.GetString("Main_Button_Title_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Main_Button_Title_Edit {
            get {
                return ResourceManager.GetString("Main_Button_Title_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Main_Button_Title_Ok {
            get {
                return ResourceManager.GetString("Main_Button_Title_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Main_Button_Title_Save {
            get {
                return ResourceManager.GetString("Main_Button_Title_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string Main_Navigation_Button {
            get {
                return ResourceManager.GetString("Main_Navigation_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gadgets.
        /// </summary>
        internal static string Main_Navigation_Entries_Gadgets {
            get {
                return ResourceManager.GetString("Main_Navigation_Entries_Gadgets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Main_Navigation_Entries_Information {
            get {
                return ResourceManager.GetString("Main_Navigation_Entries_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Main_Navigation_Entries_Settings {
            get {
                return ResourceManager.GetString("Main_Navigation_Entries_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprint.
        /// </summary>
        internal static string Page_AppInfo_Link_Title_Imprint {
            get {
                return ResourceManager.GetString("Page_AppInfo_Link_Title_Imprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        internal static string Page_AppInfo_Link_Title_PrivacyPolicy {
            get {
                return ResourceManager.GetString("Page_AppInfo_Link_Title_PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the Gadget irreversible? Warning: The whole Status-History will be deleted, too!.
        /// </summary>
        internal static string Page_GadgetDetail_Delete_Alert_Approve_Message {
            get {
                return ResourceManager.GetString("Page_GadgetDetail_Delete_Alert_Approve_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string Page_GadgetDetail_Delete_Alert_Approve_No {
            get {
                return ResourceManager.GetString("Page_GadgetDetail_Delete_Alert_Approve_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, delete.
        /// </summary>
        internal static string Page_GadgetDetail_Delete_Alert_Approve_Yes {
            get {
                return ResourceManager.GetString("Page_GadgetDetail_Delete_Alert_Approve_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0}?.
        /// </summary>
        internal static string Page_GadgetDetail_Delete_Alert_Title_Delete {
            get {
                return ResourceManager.GetString("Page_GadgetDetail_Delete_Alert_Title_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status could not be requested.
        /// </summary>
        internal static string Page_GadgetDetail_ErrorMessage_StatusTimeout {
            get {
                return ResourceManager.GetString("Page_GadgetDetail_ErrorMessage_StatusTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not available.
        /// </summary>
        internal static string Page_GadgetDetail_Fallback_NotAvailable {
            get {
                return ResourceManager.GetString("Page_GadgetDetail_Fallback_NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analytics.
        /// </summary>
        internal static string Page_GadgetDetail_H1_GadgetAnalytics {
            get {
                return ResourceManager.GetString("Page_GadgetDetail_H1_GadgetAnalytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gadgetdata.
        /// </summary>
        internal static string Page_GadgetDetail_H1_GadgetData {
            get {
                return ResourceManager.GetString("Page_GadgetDetail_H1_GadgetData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gadgetstatus.
        /// </summary>
        internal static string Page_GadgetDetail_H1_GadgetStatus {
            get {
                return ResourceManager.GetString("Page_GadgetDetail_H1_GadgetStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of Entries:.
        /// </summary>
        internal static string Page_GadgetDetail_Label_Analytics_AmountEntries {
            get {
                return ResourceManager.GetString("Page_GadgetDetail_Label_Analytics_AmountEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Temperature:.
        /// </summary>
        internal static string Page_GadgetDetail_Label_Analytics_AverageTemperature {
            get {
                return ResourceManager.GetString("Page_GadgetDetail_Label_Analytics_AverageTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature Max:.
        /// </summary>
        internal static string Page_GadgetDetail_Label_Analytics_MaxTemperature {
            get {
                return ResourceManager.GetString("Page_GadgetDetail_Label_Analytics_MaxTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature Min:.
        /// </summary>
        internal static string Page_GadgetDetail_Label_Analytics_MinTemperature {
            get {
                return ResourceManager.GetString("Page_GadgetDetail_Label_Analytics_MinTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        internal static string Page_GadgetDetail_Label_Gadget_Description {
            get {
                return ResourceManager.GetString("Page_GadgetDetail_Label_Gadget_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device ID:.
        /// </summary>
        internal static string Page_GadgetDetail_Label_Gadget_DeviceId {
            get {
                return ResourceManager.GetString("Page_GadgetDetail_Label_Gadget_DeviceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address:.
        /// </summary>
        internal static string Page_GadgetDetail_Label_Gadget_IpAddress {
            get {
                return ResourceManager.GetString("Page_GadgetDetail_Label_Gadget_IpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location:.
        /// </summary>
        internal static string Page_GadgetDetail_Label_Gadget_Location {
            get {
                return ResourceManager.GetString("Page_GadgetDetail_Label_Gadget_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gadgetname:.
        /// </summary>
        internal static string Page_GadgetDetail_Label_Gadget_Name {
            get {
                return ResourceManager.GetString("Page_GadgetDetail_Label_Gadget_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature:.
        /// </summary>
        internal static string Page_GadgetDetail_Label_Status_Temperature {
            get {
                return ResourceManager.GetString("Page_GadgetDetail_Label_Status_Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperaturestatus:.
        /// </summary>
        internal static string Page_GadgetDetail_Label_Status_TemperatureStatus {
            get {
                return ResourceManager.GetString("Page_GadgetDetail_Label_Status_TemperatureStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltage:.
        /// </summary>
        internal static string Page_GadgetDetail_Label_Status_Voltage {
            get {
                return ResourceManager.GetString("Page_GadgetDetail_Label_Status_Voltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Gadget Description.
        /// </summary>
        internal static string Page_NewGadget_Placeholder_Description {
            get {
                return ResourceManager.GetString("Page_NewGadget_Placeholder_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.0.0.0.
        /// </summary>
        internal static string Page_NewGadget_Placeholder_IpAddress {
            get {
                return ResourceManager.GetString("Page_NewGadget_Placeholder_IpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f. e. Shutter Kitchen.
        /// </summary>
        internal static string Page_NewGadget_Placeholder_Location {
            get {
                return ResourceManager.GetString("Page_NewGadget_Placeholder_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f. e. New Gadget 01.
        /// </summary>
        internal static string Page_NewGadget_Placeholder_Name {
            get {
                return ResourceManager.GetString("Page_NewGadget_Placeholder_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address is required.
        /// </summary>
        internal static string Page_NewGadget_Validation_Alert_GadgetIpAddress_Required {
            get {
                return ResourceManager.GetString("Page_NewGadget_Validation_Alert_GadgetIpAddress_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gadgetname length.
        /// </summary>
        internal static string Page_NewGadget_Validation_Alert_GadgetName_Length {
            get {
                return ResourceManager.GetString("Page_NewGadget_Validation_Alert_GadgetName_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please verify your data.
        /// </summary>
        internal static string Page_NewGadget_Validation_Alert_Title {
            get {
                return ResourceManager.GetString("Page_NewGadget_Validation_Alert_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Page_Setting_Input_Picker_Select {
            get {
                return ResourceManager.GetString("Page_Setting_Input_Picker_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Darkmode enabled.
        /// </summary>
        internal static string Page_Setting_Label_DarkmodeEnabled {
            get {
                return ResourceManager.GetString("Page_Setting_Label_DarkmodeEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification at Timeouts.
        /// </summary>
        internal static string Page_Setting_Label_NotifyWhenStatusNotRespond {
            get {
                return ResourceManager.GetString("Page_Setting_Label_NotifyWhenStatusNotRespond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Logging Active.
        /// </summary>
        internal static string Page_Setting_Label_PermissionTrackErrors {
            get {
                return ResourceManager.GetString("Page_Setting_Label_PermissionTrackErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gadgetoverview Sorting.
        /// </summary>
        internal static string Page_Setting_Label_SortingType {
            get {
                return ResourceManager.GetString("Page_Setting_Label_SortingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout for Requests in seconds.
        /// </summary>
        internal static string Page_Setting_Label_TimeoutSetting {
            get {
                return ResourceManager.GetString("Page_Setting_Label_TimeoutSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f. e. /status.
        /// </summary>
        internal static string Page_Setting_Placeholder_StatusRequestUrl {
            get {
                return ResourceManager.GetString("Page_Setting_Placeholder_StatusRequestUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Request Url.
        /// </summary>
        internal static string Page_Settings_Label_StatusRequestUrl {
            get {
                return ResourceManager.GetString("Page_Settings_Label_StatusRequestUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (ascending).
        /// </summary>
        internal static string Page_Settings_Setting_SortingType_Option_AscText {
            get {
                return ResourceManager.GetString("Page_Settings_Setting_SortingType_Option_AscText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creationdate.
        /// </summary>
        internal static string Page_Settings_Setting_SortingType_Option_ByCreation {
            get {
                return ResourceManager.GetString("Page_Settings_Setting_SortingType_Option_ByCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Page_Settings_Setting_SortingType_Option_ByLocation {
            get {
                return ResourceManager.GetString("Page_Settings_Setting_SortingType_Option_ByLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Page_Settings_Setting_SortingType_Option_ByName {
            get {
                return ResourceManager.GetString("Page_Settings_Setting_SortingType_Option_ByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        internal static string Page_Settings_Setting_SortingType_Option_ByTemperature {
            get {
                return ResourceManager.GetString("Page_Settings_Setting_SortingType_Option_ByTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (descending).
        /// </summary>
        internal static string Page_Settings_Setting_SortingType_Option_DescText {
            get {
                return ResourceManager.GetString("Page_Settings_Setting_SortingType_Option_DescText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        internal static string Page_Settings_Setting_Timeout_Measurement {
            get {
                return ResourceManager.GetString("Page_Settings_Setting_Timeout_Measurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Information.
        /// </summary>
        internal static string Page_Title_AppInfo {
            get {
                return ResourceManager.GetString("Page_Title_AppInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Page_Title_EditGadget {
            get {
                return ResourceManager.GetString("Page_Title_EditGadget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        internal static string Page_Title_GadgetOverview {
            get {
                return ResourceManager.GetString("Page_Title_GadgetOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprint.
        /// </summary>
        internal static string Page_Title_Imprint {
            get {
                return ResourceManager.GetString("Page_Title_Imprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Gadget.
        /// </summary>
        internal static string Page_Title_NewGadget {
            get {
                return ResourceManager.GetString("Page_Title_NewGadget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        internal static string Page_Title_PrivacyPolicy {
            get {
                return ResourceManager.GetString("Page_Title_PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Page_Title_Settings {
            get {
                return ResourceManager.GetString("Page_Title_Settings", resourceCulture);
            }
        }
    }
}
